name: Autosend

on:
  push:
    branches: master
  schedule:
    - cron: '30 0 */10 * *' # 每10天的UTC时间08:30执行
  workflow_dispatch:
    inputs: {}

jobs:
  autosend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare Message
        id: prepare_message
        run: |
          # 随机选择一条中文闲聊消息
          messages=("今天的天气真不错，适合出去走走！你有计划吗？" 
                    "最近在追什么剧吗？我觉得那部新剧挺好看的！" 
                    "外面好热啊，真想待在空调房里。你呢？" 
                    "你最近有没有读到什么好书？推荐给我吧！" 
                    "这个周末有空吗？我们可以一起去看电影！" 
                    "刚刚看到一个搞笑视频，笑得我肚子都疼了！")
          random_message=${messages[$RANDOM % ${#messages[@]}]}
          echo "MESSAGE=$random_message" >> $GITHUB_ENV

      - name: Send Message to GroupMe
        uses: joelwmale/webhook-action@master
        with:
          url: "https://api.groupme.com/v3/bots/post"
          body: '{"text": "${{ env.MESSAGE }}", "bot_id": "${{ secrets.GM_BOT_ID }}" }'
      
      - name: Random Delay
        run: |
          # 添加随机延迟，范围为 1 到 5 分钟
          delay=$((RANDOM % 300 + 60)) # 60 到 360 秒
          echo "Sleeping for $delay seconds..."
          sleep $delay
