name: Autosend

on:
  push:
    branches: master
  schedule:
    - cron: '30 0 */10 * *' # 每10天的UTC时间08:30执行
  workflow_dispatch:
    inputs: {}

jobs:
  autosend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare Random Chat Message
        id: prepare_message
        run: |
          # 随机选择一条闲聊消息
          messages=(
            "Hey! How's your day going?"
            "Did you catch the latest episode of that show we like?"
            "What are your plans for the weekend?"
            "I tried that new coffee place yesterday. It was amazing!"
            "Have you read any good books lately?"
            "What's your favorite movie right now?"
            "I just got back from hiking. The views were incredible!"
            "Are you still working on that project? How's it coming along?"
            "I found a great recipe for dinner. Want me to share it?"
            "Did you hear about that new game coming out? Looks fun!"
          )
          random_message=${messages[$RANDOM % ${#messages[@]}]}
          echo "MESSAGE=$random_message" >> $GITHUB_ENV

      - name: Send Message to GroupMe
        uses: joelwmale/webhook-action@master
        with:
          url: "https://api.groupme.com/v3/bots/post"
          body: '{"text": "${{ env.MESSAGE }}", "bot_id": "${{ secrets.GM_BOT_ID }}" }'
      
      - name: Random Delay
        run: |
          # 添加随机延迟，范围为 1 到 5 分钟
          delay=$((RANDOM % 300 + 60)) # 60 到 360 秒
          echo "Sleeping for $delay seconds..."
          sleep $delay
